---
title: "CodeBook"
output: html_document
---

The original dataset is the UCI HAR dataset.

The output dataset contained in the file second_ds.txt has 180 observations of
68 variables (180 rows and 68 columns)

The 180 observations (rows) correspond one to each of the possible combinations of 
30 subjects and 6 activities. Note that both test and training subjects from the
original dataset where merged into a single dataset.

The columns names are available at the first row of the file and correspond to:

1) Subject -    Integer from 1 to 30, corresponding to each of the 30 subjects 
                participating in the experiment. 
2) Activity -   Factor indicating each of the six possible activities performed
                by the subjects during the experiment.

>
> Observations valid for variables 3 to 68:
>
>       a)       variable names starting by a "t" correspond to time-domain 
>                measurements and variables names starting by a "f" correspond to
>                frequency-domain measurements.
>
>       b)       all variables where obtained by averaging the measurements from 
>                the original dataset (UCI HAR dataset) over each pair (Subject,
>                activity).

3) tBodyAcc-mean()-X 
4) tBodyAcc-mean()-Y
5) tBodyAcc-mean()-Z
6) tBodyAcc-std()-X
7) tBodyAcc-std()-Y
8) tBodyAcc-std()-Z
9) tGravityAcc-mean()-X
10) tGravityAcc-mean()-Y
11) tGravityAcc-mean()-Z
12) tGravityAcc-std()-X
13) tGravityAcc-std()-Y
14) tGravityAcc-std()-Z
15) tBodyAccJerk-mean()-X
16) tBodyAccJerk-mean()-Y
17) tBodyAccJerk-mean()-Z
18) tBodyAccJerk-std()-X
19) tBodyAccJerk-std()-Y
20) tBodyAccJerk-std()-Z
21) tBodyGyro-mean()-X
22) tBodyGyro-mean()-Y       
23) tBodyGyro-mean()-Z
24) tBodyGyro-std()-X
25) tBodyGyro-std()-Y
26) tBodyGyro-std()-Z        
27) tBodyGyroJerk-mean()-X
28) tBodyGyroJerk-mean()-Y
29) tBodyGyroJerk-mean()-Z
30) tBodyGyroJerk-std()-X      
31) tBodyGyroJerk-std()-Y
32) tBodyGyroJerk-std()-Z
33) tBodyAccMag-mean()
34) tBodyAccMag-std()          
35) tGravityAccMag-mean()
36) tGravityAccMag-std()
37) tBodyAccJerkMag-mean()
38) tBodyAccJerkMag-std()
39) tBodyGyroMag-mean()
40) tBodyGyroMag-std()
41) tBodyGyroJerkMag-mean()
42) tBodyGyroJerkMag-std()     
43) fBodyAcc-mean()-X
44) fBodyAcc-mean()-Y
45) fBodyAcc-mean()-Z
46) fBodyAcc-std()-X           
47) fBodyAcc-std()-Y
48) fBodyAcc-std()-Z
49) fBodyAccJerk-mean()-X
50) fBodyAccJerk-mean()-Y      
51) fBodyAccJerk-mean()-Z
52) fBodyAccJerk-std()-X
53) fBodyAccJerk-std()-Y
54) fBodyAccJerk-std()-Z       
55) fBodyGyro-mean()-X
56) fBodyGyro-mean()-Y
57) fBodyGyro-mean()-Z
58) fBodyGyro-std()-X          
59) fBodyGyro-std()-Y
60) fBodyGyro-std()-Z
61) fBodyAccMag-mean()
62) fBodyAccMag-std()          
63) fBodyBodyAccJerkMag-mean()
64) fBodyBodyAccJerkMag-std()
65) fBodyBodyGyroMag-mean()
66) fBodyBodyGyroMag-std()     
67) fBodyBodyGyroJerkMag-mean()
68) fBodyBodyGyroJerkMag-std()  

